version: "3.8"

services:
  proxy:
    image: nginx:alpine
    container_name: proxy-server
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80