version: "3.8"

services:
  client:
    image: client
    container_name: client
    networks:
      - devops
      - local_network
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./client.dockerfile

  api:
    image: api
    container_name: api
    networks:
      - devops
      - local_network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - SEQ_SERVER_URL=${SEQ_SERVER_URL}
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./api.dockerfile
    depends_on:
      - postgres
      - seq

  seq:
    image: datalust/seq
    container_name: seq
    networks:
      - local_network
    environment:
      - ACCEPT_EULA=Y
    restart: unless-stopped
    # ports:
    #   - 5341:80

  postgres:
    image: postgres
    container_name: postgres
    networks:
      - local_network
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    # ports:
    #   - 5432:5432
    build:
      context: .
      dockerfile: ./postgres.dockerfile

networks:
  devops:
    name: tatar
  local_network: