version: "3.8"

services:
  proxy:
    image: nginx:alpine
    container_name: proxy-server
    networks:
      - devops
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    ports:
      - 80:80
    # depends_on:
    #   - client
    #   - api

networks: 
  devops:
    external: true
    name: tatar